// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"toubiaogo/app/model/internal"
)

// Tender is the golang structure for table tender.
type Tender internal.Tender

// Fill with you ideas below.
