// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Tender is the golang structure for table tender.
type Tender struct {
	Id       int         `orm:"id,primary" json:"id"`       //
	Name     string      `orm:"name"       json:"name"`     //
	Data     string      `orm:"data"       json:"data"`     //
	UpdateAt *gtime.Time `orm:"update_at"  json:"updateAt"` //
	CreateAt *gtime.Time `orm:"create_at"  json:"createAt"` //
}
