// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id       int         `orm:"id,primary" json:"id"`       //
	Username string      `orm:"username"   json:"username"` //
	Password string      `orm:"password"   json:"password"` //
	UpdateAt *gtime.Time `orm:"update_at"  json:"updateAt"` //
	CreateAt *gtime.Time `orm:"create_at"  json:"createAt"` //
}
